#!/bin/sh

echo "Making..."
rm -rf bin/server_* bin/client
cd src/clientserver
make cleaner
make
cd ..
make clean
make
cd ..
mv src/server_mem bin/server_mem
mv src/server_disk bin/server_disk
mv src/client bin/client
echo "Done making, enjoy the binaries!"
